#index:
#    path: /
#    controller: App\Controller\DefaultController::index

medicos:
    path: /medicos
    controller: App\Controller\MedicosController::getAll
    methods: GET

especialidades:
    path: /especialidades
    controller: App\Controller\EspecialidadesController::getAll
    methods: GET
